### ISSUE TITLE
There is no code

### ISSUE THREAD

**Issue by brianium** [mrkrstphr/dbunit-fixture-arrays#1]
I want to see some code, but there is none.

**Comment by austinsmorris** [comment]
![yay](https://cloud.githubusercontent.com/assets/1616868/3933488/f9709008-247f-11e4-90a8-f2737a70a08e.gif)

**Comment by brianium** [comment]
:+1:

**Comment by austinsmorris** [comment]
Is this still an issue?  I can see code now...

**Comment by brianium** [comment]
:+1:

**Comment by mrkrstphr** [comment]
:dancers:
